-- +goose Up
ALTER TABLE products MODIFY COLUMN price BIGINT NOT NULL DEFAULT 0;
ALTER TABLE transactions MODIFY COLUMN total_amount BIGINT NOT NULL;
ALTER TABLE transaction_items MODIFY COLUMN price BIGINT NOT NULL;
ALTER TABLE transaction_items MODIFY COLUMN subtotal BIGINT NOT NULL;

-- +goose Down
ALTER TABLE products MODIFY COLUMN price DECIMAL(15,2) NOT NULL DEFAULT 0;
ALTER TABLE transactions MODIFY COLUMN total_amount DECIMAL(15,2) NOT NULL;
ALTER TABLE transaction_items MODIFY COLUMN price DECIMAL(15,2) NOT NULL;
ALTER TABLE transaction_items MODIFY COLUMN subtotal DECIMAL(15,2) NOT NULL;
